name: Slack Notification
description: This action to send a slack notification

inputs:
  text_message:
    description: This is the message that will be sent to slack
    default: 'Success on job'
    required: false


runs:
  using: "composite"
  steps:
    - name: Run e2e tests
      run: echo "This is the message ${{ inputs.text_message }}"
      shell: bash
