name: Setup Environment
description: This is a helper to setup the py environment

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.24"

    - name: Sync dependencies
      run: uv sync --locked
      shell: bash

    - name: Force fail
      shell: bash
      run: |
        echo "Force fail now..."
        exit 1
