name: Dev Deploy

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      # - name: Setup env
      #   uses: ./.github/actions/deploy-ecr
      #   with:
      #     ENV: dev

      # - name: Slack notification
      #   uses: ./.github/actions/slack-notification
      #   with:
      #     text_message: "result ? success : failure"

      - name: Deploy
        id: deploy
        uses: ./.github/actions/deploy-ecr
        with:
          ENV: dev

      - name: Trigger Test
        if: always() && steps.deploy.outputs.result == 'success'
        uses: ./.github/actions/trigger-test

