name: Manual Trigger

on:
  workflow_dispatch:
    # inputs:
    #   branch:
    #     description: 'Branch to deploy'
    #     required: true
    #     default: 'main'

env:
  POTATO: 'this is a env POTATO'
  GIT_BRANCH_SELECTED: ${{ github.ref_name }}

jobs:
  verify_custom_branch_allowed:

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_BRANCH_SELECTED }}

      - name: Verify branch name
        run: |
          BLOCKED_BRANCHES="dev stage"
          for blocked in $BLOCKED_BRANCHES; do
            if [[ "${GIT_BRANCH_SELECTED}" == "$blocked" ]]; then
              echo "This workflow can't be run on the '$blocked' branch."
              exit 1
            fi
          done


  run-manually:
    needs: verify_custom_branch_allowed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          # ref: ${{ github.event.inputs.branch }}


      - name: Show workflow file branch
        run: |
          echo "Workflow file branch ref: ${{ github.ref }}"
          echo "Workflow file branch name: ${{ github.ref_name }}"
          echo "This is the env of gitname ${{ env.GIT_BRANCH }}"


      - name: Checkout branch selecionada
        run: git checkout ${{ github.event.inputs.branch }}
      - name: Git status
        run: git status

      # - name: Git status2
      #   run: ${{ github.event.inputs.branch }}

      # - name: Git status3
      #   run: ${{ github.ref }}

      - name: Show workflow file branch
        run: |
          echo "Workflow file branch ref: ${{ github.ref }}"
          echo "Workflow file branch name: ${{ github.ref_name }}"
