name: Manual Trigger

on:
  workflow_dispatch:

env:
  POTATO: 'this is a env POTATO'
  GIT_BRANCH_SELECTED: ${{ github.ref_name }}

jobs:
  verify_custom_branch_allowed:
    runs-on: ubuntu-latest
    steps:
      - name: Show default branch value
        run: echo "Default value: $GIT_BRANCH_SELECTED"

      - name: Change branch value
        run: |
          echo "GIT_BRANCH_SELECTED=my-new-value" >> $GITHUB_ENV

      - name: Show updated branch value
        run: echo "Updated value: $GIT_BRANCH_SELECTED"

      - name: Use updated value in logic
        run: |
          if [[ "$GIT_BRANCH_SELECTED" == "my-new-value" ]]; then
            echo "Branch successfully changed!"
          else
            echo "Branch not changed!"
            exit 1
          fi

  run-manually:
    needs: verify_custom_branch_allowed
    runs-on: ubuntu-latest
    steps:
      - name: Show inherited branch value
        run: echo "Inherited value: $GIT_BRANCH_SELECTED"
