name: Sonarqube

on:
  pull_request:
    # branches:
    #   - to-be-defined

jobs:
  run-tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup env
        uses: ./.github/actions/setup-env
        timeout-minutes: 90

      - name: Run Tests
        uses: ./.github/actions/run-tests
        id: run-tests

      - name: List workspace files
        run: ls -R

      - name: Archive code coverage results
        id: archive-coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
          retention-days: 1

      - name: SonarQube Scan
        uses: ./.github/actions/sonarqube

