name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - stage

permissions:
  pull-requests: write

jobs:
  run-tests:
    strategy:
      # Run all tests to provide feedback on full branch
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      # - name: Setup env
      #   uses: ./.github/actions/setup-env
      #   timeout-minutes: 10

      # - name: Run Tests
      #   id: run-tests
      #   uses: ./.github/actions/run-tests

      # - name: Comment on PR
      #   if: always() && (steps.run-tests.conclusion == 'success' || steps.run-tests.conclusion == 'failure')
      #   uses: ./.github/actions/comment-status-on-pr

      # - name: Create a PR status badge
      #   if: always() && (steps.run-tests.conclusion == 'success' || steps.run-tests.conclusion == 'failure')
      #   uses: ./.github/actions/create-pr-badge
