name: Unit Tests

on:
  pull_request:


permissions:
  pull-requests: write

jobs:
  run-tests:
    strategy:
      # Run all tests to provide feedback on full branch
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup env
        uses: ./.github/actions/setup-env
        timeout-minutes: 90

      - name: Run Tests
        uses: ./.github/actions/run-tests
        # with:
        #   export-coverage: 'false'

      - name: Comment on PR
        if: always()
        uses: ./.github/actions/comment-status-on-pr

      - name: Create a PR status badge
        if: always()
        uses: ./.github/actions/create-pr-badge
